# Generated by Django 5.2.7 on 2025-11-03 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(default='2025-12-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_end',
            field=models.DateField(default='2025-12-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_start',
            field=models.DateField(default='2025-11-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(default='2025-12-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
