# Generated by Django 5.2.7 on 2025-11-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_registration_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRuleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_rules', to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('rule_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tournament.tournamentruletitle')),
            ],
        ),
    ]
