# Generated by Django 5.2.7 on 2025-11-03 17:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournamentruletitle_tournamentrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_process',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
