# Generated by Django 5.2.7 on 2025-11-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_tournament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
