# Generated by Django 5.2.7 on 2025-11-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_logo'),
        ('tournament', '0008_tournament_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='last_champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='championships_won', to='team.team'),
        ),
    ]
