# Generated by Django 5.2.7 on 2025-11-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0008_tournament_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('match_date_time', models.DateTimeField()),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('team_a_score', models.CharField(blank=True, max_length=100, null=True)),
                ('team_b_score', models.CharField(blank=True, max_length=100, null=True)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
