# Generated by Django 5.2.7 on 2025-11-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_fixture', '0001_initial'),
        ('team', '0002_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfixture',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='team.team'),
        ),
        migrations.AlterField(
            model_name='matchfixture',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='team.team'),
        ),
    ]
