# Generated by Django 5.2.7 on 2025-10-31 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton')], default='cricket', max_length=30)),
                ('image', models.ImageField(upload_to='bcc-members/')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bcc_member_roles', to='role.role')),
            ],
        ),
    ]
