# Generated by Django 5.2.7 on 2025-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bccmember',
            name='category',
        ),
        migrations.AlterField(
            model_name='bccmember',
            name='image',
            field=models.ImageField(upload_to='bcc_members/'),
        ),
    ]
