# Generated by Django 5.2.7 on 2025-11-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc_member', '0002_remove_bccmember_category_alter_bccmember_image'),
        ('role', '0002_role_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bccmember',
            name='category',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton')], default='cricket', max_length=50),
        ),
        migrations.AlterField(
            model_name='bccmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role'),
        ),
    ]
