# Generated by Django 5.2.7 on 2025-11-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcc_member', '0003_bccmember_category_alter_bccmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bccmember',
            name='category',
        ),
    ]
