# Generated by Django 5.2.7 on 2025-10-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bkash_transcation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
