# Generated by Django 5.2.7 on 2025-10-29 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_bkash_transcation_id'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_players', to='tournament.tournament'),
        ),
    ]
