# Generated by Django 5.2.7 on 2025-10-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_role_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='bkash_transcation_id',
            new_name='bkash_transaction_id',
        ),
    ]
