# Generated by Django 5.2.7 on 2025-10-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_rename_bkash_transcation_id_player_bkash_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
