# Generated by Django 5.2.7 on 2025-10-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bkash_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
