# Generated by Django 5.2.7 on 2025-11-04 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
