# Generated by Django 5.2.7 on 2025-10-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
