# Generated by Django 5.2.7 on 2025-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
